// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApP8mGDrmZIFY1mUn9_pe76XRnl6tsqTY',
    appId: '1:643004916340:web:42520705c44f9441b36721',
    messagingSenderId: '643004916340',
    projectId: 'neuro-conecta',
    authDomain: 'neuro-conecta.firebaseapp.com',
    storageBucket: 'neuro-conecta.firebasestorage.app',
    measurementId: 'G-NBD1WQT8GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcpg4GOtMXTXjS-BG6mz4K-sptZSK1dUE',
    appId: '1:643004916340:android:79a0e6cf3f67bb86b36721',
    messagingSenderId: '643004916340',
    projectId: 'neuro-conecta',
    storageBucket: 'neuro-conecta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsEGi2S0GksthlxcME2JfGYWO5gy6FLBY',
    appId: '1:643004916340:ios:e17a35a4d3d0c563b36721',
    messagingSenderId: '643004916340',
    projectId: 'neuro-conecta',
    storageBucket: 'neuro-conecta.firebasestorage.app',
    iosBundleId: 'com.example.neuroConecta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsEGi2S0GksthlxcME2JfGYWO5gy6FLBY',
    appId: '1:643004916340:ios:e17a35a4d3d0c563b36721',
    messagingSenderId: '643004916340',
    projectId: 'neuro-conecta',
    storageBucket: 'neuro-conecta.firebasestorage.app',
    iosBundleId: 'com.example.neuroConecta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApP8mGDrmZIFY1mUn9_pe76XRnl6tsqTY',
    appId: '1:643004916340:web:931f901ef1374c79b36721',
    messagingSenderId: '643004916340',
    projectId: 'neuro-conecta',
    authDomain: 'neuro-conecta.firebaseapp.com',
    storageBucket: 'neuro-conecta.firebasestorage.app',
    measurementId: 'G-03JHB86PZZ',
  );

}