// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAESMB3R-l0u0o40cwyiquA9H1EZx7E610',
    appId: '1:95970348842:web:7611836d71077670e51853',
    messagingSenderId: '95970348842',
    projectId: 'fir-41be9',
    authDomain: 'fir-41be9.firebaseapp.com',
    storageBucket: 'fir-41be9.firebasestorage.app',
    measurementId: 'G-XYXHQ8M1JX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOAtaybtB14Tu-AIXONppmeW60ij0Y0e8',
    appId: '1:95970348842:android:cedc838f1f3d5732e51853',
    messagingSenderId: '95970348842',
    projectId: 'fir-41be9',
    storageBucket: 'fir-41be9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzp2byL8q23vwpMc-kZNWGpayYe4U2Aa8',
    appId: '1:95970348842:ios:67bdbbb9319ac6c8e51853',
    messagingSenderId: '95970348842',
    projectId: 'fir-41be9',
    storageBucket: 'fir-41be9.firebasestorage.app',
    iosBundleId: 'com.example.neuroConecta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzp2byL8q23vwpMc-kZNWGpayYe4U2Aa8',
    appId: '1:95970348842:ios:67bdbbb9319ac6c8e51853',
    messagingSenderId: '95970348842',
    projectId: 'fir-41be9',
    storageBucket: 'fir-41be9.firebasestorage.app',
    iosBundleId: 'com.example.neuroConecta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAESMB3R-l0u0o40cwyiquA9H1EZx7E610',
    appId: '1:95970348842:web:3af53025ea6cb351e51853',
    messagingSenderId: '95970348842',
    projectId: 'fir-41be9',
    authDomain: 'fir-41be9.firebaseapp.com',
    storageBucket: 'fir-41be9.firebasestorage.app',
    measurementId: 'G-MBCGN0PTTR',
  );
}
